version: "3.8"

services:
  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      frappe:
    restart: unless-stopped

  redis-cache:
    image: redis:6.2-alpine
    networks:
      frappe:
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    networks:
      frappe:
    restart: unless-stopped

  backend:
    image: local/erpnext-hrms:latest
    build:
      context: .
      dockerfile: Containerfile
      args:
        FRAPPE_BRANCH: ${FRAPPE_BRANCH:-version-16}
        APPS_JSON_BASE64: ${APPS_JSON_BASE64}
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      frappe:
    restart: unless-stopped

  frontend:
    image: local/erpnext-hrms:latest
    depends_on:
      - backend
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      frappe:
    restart: unless-stopped
    ports:
      - "8090:8080"

  websocket:
    image: local/erpnext-hrms:latest
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      frappe:
    restart: unless-stopped

  scheduler:
    image: local/erpnext-hrms:latest
    command: ["bench", "schedule"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      frappe:
    restart: unless-stopped

  worker:
    image: local/erpnext-hrms:latest
    command: ["bench", "worker", "--queue", "short,default,long"]
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      frappe:
    restart: unless-stopped

volumes:
  db-data:
  sites:
  logs:

networks:
  frappe:
    driver: bridge
